### PR TITLE
Upgrade to Spark 2.1

### PR DESCRIPTION
**Pull request by medvekoma**

### CODE REVIEW

**Comment by JohnAdders** [comment]
Looks good thanks

Out of interest, what's going on with the swapping of the imports? for example

-import java.io.{DataOutputStream, BufferedOutputStream}
 +import java.io.{BufferedOutputStream, DataOutputStream}

**Comment by medvekoma** [comment]
Nothing, it was reordered by IntelliJ - probably alphabetical order. Shall I change back for clarity?

**Comment by medvekoma** [comment]
Imports are no more swapped

**Comment by JohnAdders** [comment]
That's great thanks

**Pull request merged**
