### PR TITLE
fix classpath (wildcards not supported)

### PR DESCRIPTION
**Pull request by medvekoma**
Reading from S3 was not working

### CODE REVIEW

**Comment by medvekoma** [comment]
Closing for now, will resubmit

**Comment by medvekoma** [comment]
I am reopening this change - it enables accessing S3 files on EMR.

**Comment by JohnAdders** [comment]
I'm not very happy about the emr hard coded paths in init which I must have missed before.
Can we add these as environment variables or simply add them to CLASSPATH outside the julia code?

**Comment by medvekoma** [comment]
Hi @JohnAdders, I am not happy with that either. I implemented a more generic solution (that reads the class path from spark-defaults.conf), but then I found out that @aviks is working on the same solution, so we agreed that he will push that change to dxdf, and it will come back from there.

**Comment by JohnAdders** [comment]
OK Thanks

**Pull request merged**
